### ISSUE TITLE
Tests fail against Python 3.x

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/basictracer-python#16]
Per @cybergrind's [comment](https://github.com/opentracing/basictracer-python/pull/15#issuecomment-241208957):

> Unfortunately protobuf tests aren't fine on python 3 due discrepancies in implementation of bytearray support
> https://travis-ci.org/opentracing/basictracer-python/jobs/153806259
> Looks like https://github.com/google/protobuf/issues/1173 caused it
> 
> I believe we can get rid of jumpahead now just to not break current applications that aren't rely on protobuf serialization and fix tests in separate branch. Btw it isn't look like it going to be fixed in nearest future in protobuf repo.

**Comment by tedsuo** [comment]
PR #20 fixes this.

**Comment by bhs** [comment]
As @tedsuo mentioned, this was fixed by #20.
