### ISSUE TITLE
Dependency on futures library

### ISSUE THREAD

**Issue by MichaelHills** [opentracing/basictracer-python#21]
It looks like `setup.py` depends on https://pypi.python.org/pypi/futures but doesn't use it anywhere in the code. Was it intended to depend on https://pypi.python.org/pypi/future ? Note the singular `future`, not the plural `futures`.

I had some weird bug where this `concurrent.futures` library was shadowing the python3.5 built-in library which led me here. Although I can't repro my original problem anymore it seemed strange that this package depends on `futures`.

**Comment by yurishkuro** [comment]
It's probably a leftover from earlier implementations.
